imports:
    - { resource: "@CaramiaAdminBundle/Resources/config/services.yml" }

parameters:
    caramia_admin.default_username: admin@caramia.fr
    caramia_admin.default_password: caramia

security:
    encoders:
        Caramia\AdminBundle\Entity\UserInterface: sha512

    providers:
        database_users:
            entity: { class: CaramiaAdminBundle:User, property: email }

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/request-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }


sonata_admin:
    templates:
        layout:                         CaramiaAdminBundle::standard_layout.html.twig
        ajax:                           SonataAdminBundle::ajax_layout.html.twig
        list:                           CaramiaAdminBundle:CRUD:list.html.twig
        show:                           SonataAdminBundle:CRUD:show.html.twig
        show_compare:                   SonataAdminBundle:CRUD:show_compare.html.twig
        edit:                           CaramiaAdminBundle:CRUD:edit.html.twig
        history:                        SonataAdminBundle:CRUD:history.html.twig
        preview:                        SonataAdminBundle:CRUD:preview.html.twig
        delete:                         SonataAdminBundle:CRUD:delete.html.twig
        batch:                          SonataAdminBundle:CRUD:list__batch.html.twig
        acl:                            SonataAdminBundle:CRUD:acl.html.twig
        action:                         SonataAdminBundle:CRUD:action.html.twig
        select:                         SonataAdminBundle:CRUD:list__select.html.twig
        filter:                         CaramiaAdminBundle:Form:filter_admin_fields.html.twig
        dashboard:                      CaramiaAdminBundle:Core:dashboard.html.twig
        search:                         SonataAdminBundle:Core:search.html.twig
        batch_confirmation:             CaramiaAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:                 SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:                SonataAdminBundle:CRUD:base_list_field.html.twig
        list_block:                     SonataAdminBundle:Block:block_admin_list.html.twig
        user_block:                     CaramiaAdminBundle:Core:user_block.html.twig
        add_block:                      SonataAdminBundle:Core:add_block.html.twig
        pager_links:                    SonataAdminBundle:Pager:links.html.twig
        pager_results:                  SonataAdminBundle:Pager:results.html.twig
        tab_menu_template:              SonataAdminBundle:Core:tab_menu_template.html.twig
        history_revision_timestamp:     SonataAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:       SonataAdminBundle:Helper:short-object-description.html.twig
        search_result_block:            SonataAdminBundle:Block:block_search_result.html.twig
        action_create:                  SonataAdminBundle:CRUD:dashboard__action_create.html.twig
        button_acl:                     SonataAdminBundle:Button:acl_button.html.twig
        button_create:                  SonataAdminBundle:Button:create_button.html.twig
        button_edit:                    SonataAdminBundle:Button:edit_button.html.twig
        button_history:                 SonataAdminBundle:Button:history_button.html.twig
        button_list:                    SonataAdminBundle:Button:list_button.html.twig
        button_show:                    SonataAdminBundle:Button:show_button.html.twig
        knp_menu_template:              CaramiaAdminBundle:Menu:sonata_menu.html.twig

    title: Administration
    options:
        title_mode: single_text

    # dashboard:
    #     blocks:
    #         - { position: left, type: sonata.admin.block.admin_list }

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

        sonata.admin.block.stats: ~
        caramia.block.counter: ~
        caramia.block.shortlist: ~

sonata_intl:
    timezone:
        default: Europe/Paris
        locales:
            fr:    Europe/Paris
twig:
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
