admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

caramia_admin:
    resource: "@CaramiaAdminBundle/Controller/"
    type: annotation
    # resource: "@TrackerBundle/Resources/config/routing.yml"
    prefix: /admin
